#!/usr/bin/python3
import sys
import ctypes
import struct
import json
import subprocess

def send_message(message):
    # Write message size.
    sys.stdout.write(struct.pack('I', len(message)))
    # Write the message itself.
    sys.stdout.write(message)
    sys.stdout.flush()

while True:
    text_length_bytes = sys.stdin.buffer.read(4)
    if len(text_length_bytes) == 0:
        sys.exit(0)
    text_length = struct.unpack('i', text_length_bytes)[0]
    text = sys.stdin.buffer.read(text_length).decode('utf-8')
    t = json.loads(text)
    subprocess.run(['C:\\Python34\\Scripts\\you-get.exe', '-p', 'D:\\mpv\\mpv.exe', t['text']])
    #start_new_session=True
    #ctypes.windll.user32.MessageBoxW(None, t['text'], 'title', 0)
